sonar.sources=src
sonar.exclusions=public/**,**/public/**,frontend/app/public/**
sonar.coverage.exclusions=public/**,**/public/**,frontend/app/public/**
sonar.cpd.exclusions=public/**,**/public/**,frontend/app/public/**
