export interface ArticleType {
    node:{
        image1x1Url?:string,
        image4x3Url?:string,
        image16x9Url?:string,
        id?:string,
        title?:string,
        altImage?:string,
        category?:string,
        author?:{
            firstname?:string,
            lastname?:string,
            bio?:string,
        dob?:string,
        avatarUrl?:string,
    },
    badgeColor?:string,
    featuredType?:string,
    videoLink?:string,
    body?:string,
    created?:string,
    briefsummary?:string
}
}